### PR TITLE
Additions

### PR DESCRIPTION
**Pull request by davidmpaz**
Hello,

please would you consider to add these commits to main stream? 

I know  there are several and critic changes but i think it would be nice to have all of these implemented here. 

I will try to summarize all changes.

* Add multiple projects support. This is done by adding a new Project model taking information from settings, database tables for translations and keys were updated also. In future it could be added to database without too much more effort. Current project in work is kept in session as global variable.
* Add composer support. Install Zend framework and phpunit by composer.
* Test were failing. So test set up also is updated. Add also a travis configuration, check [Build Status](https://travis-ci.org/davidmpaz/oTranCe)
* Add basic REST controller to interact with application. The current export/import implementation was not enough for us. No Zend_Rest used since the setup would be more than the real usage later on.
* Add action to translate in bulk from configured external services.
* Refactored also the interface to allow faster translation/edition by using `tab` on strings to translate.

Many thanks in advance for your time and for this project.

David

### CODE REVIEW

**Comment by DSB** [comment]
Hi David,
thank you ver ymuch for your work. I'll be happy to check your additions. Especially the multi project feature is interesting for many users. The upcoming long weekend will be perfect to watch the diff. ;)

**Comment by davidmpaz** [comment]
Hi @DSB,

Any news regarding these changes?

**Comment by DSB** [comment]
Thanks for the reminder. I totally forgot about it. :(
I will review it today.

**Comment by DSB** [comment]
Thank you so much for the work you invested here. This is going into the right direction and I really appreciate the result. Keep up the good work. ;)
Sorry again that it took such a long time until I found my time to review that.

**Comment by davidmpaz** [comment]
Cool!! .. Thanks to you for creating and share it in the first place.

Cheers

**Pull request merged**
